- type: replace
  path: /vm_extensions?/-
  value:
    name: worker-lb
    cloud_properties:
      lb_target_groups:
      - demo-cfcr-scgw-https
      - demo-cfcr-ingress-https
      - demo-prometheus-proxy
      security_groups:
      - demo-prometheus-proxy
      - demo-bosh-vms
