- type: replace
  path: /vm_extensions?/-
  value:
    name: master-lb
    cloud_properties:
      lb_target_groups:
      - demo-bosh-master
      - demo-cfcr-uaa
      security_groups:
      - demo-bosh-master
      - demo-bosh-vms
